import type { Product } from "@/lib/types";

/**
 * Inventory.
 *
 * The four items marked `draft: false` are the operator's real products, typed
 * from the PDFs supplied on 25 Aug 2026 — descriptions, stop durations,
 * inclusions and the per-vehicle price list are theirs, not ours. Everything
 * still marked `draft: true` is placeholder inventory awaiting the rest of the
 * list (more tours were promised the same week).
 *
 * Pricing is **per vehicle**, in USD. `fromPrice` is the cheapest vehicle so the
 * cards have a single figure; `pricing` carries the full list the detail pages
 * show. Never present a "from" figure as a per-person price.
 */

const PRICE_NOTE = "PLACEHOLDER — awaiting client pricing";
const PER_VEHICLE = "Per vehicle, not per person";

/** Every tour is driven by the same multilingual driver-guide team. */
const GUIDE_LANGUAGES = ["Hindi", "Arabic", "English", "French", "Urdu"];

export const products: Product[] = [
  {
    slug: "seven-coloured-earth-south-coast",
    productType: "tour",
    title: "Seven Coloured Earth & South Coast Wonders",
    hook: "Coloured earth, a sacred crater lake and the island's wildest gorges.",
    summary:
      "The stunning landscapes and rich cultural heritage of the south coast in one day: the Chamarel Seven Coloured Earth Geopark, the sacred lake of Grand Bassin, the Black River Gorges and Alexandra Falls, with panoramic views from the Trou aux Cerfs volcanic crater and a stop at the Le Port ship-model workshop along the way.",
    region: "South",
    duration: "6–7 hours",
    fromPrice: 84,
    currency: "USD",
    priceNote: PER_VEHICLE,
    pricing: [
      { vehicle: "Car", capacity: "Up to 3 people", price: 84 },
      { vehicle: "Van", capacity: "5 to 10 people", price: 125 },
    ],
    languages: GUIDE_LANGUAGES,
    accessibility: ["Not wheelchair accessible", "Infant seats available", "Suitable for all ages"],
    groupType: "Private",
    highlights: [
      "Chamarel Seven Coloured Earth Geopark",
      "Grand Bassin (Ganga Talao), the sacred crater lake",
      "Panoramas from Trou aux Cerfs and Alexandra Falls",
      "Black River Gorges viewpoint",
      "Handcrafted ship models at the Le Port workshop",
    ],
    included: ["Air-conditioned vehicle", "Small bottle of water", "Hotel pickup and drop-off"],
    excluded: ["Lunch", "Entry/admission — Chamarel Seven Coloured Earth Geopark"],
    itinerary: [
      { title: "Hotel pickup", description: "Collection from your hotel or accommodation at the time you choose." },
      { title: "Le Port Ship Model, Vacoas — 30 min", description: "Watch artisans handcraft wooden ship models, then browse a showroom of finished vessels celebrating the island's maritime heritage." },
      { title: "Trou aux Cerfs, Curepipe — 40 min", description: "A dormant volcanic crater 605m above sea level, ringed by forest, with a 360-degree view over Curepipe and the Rempart, Trois Mamelles and Moka peaks." },
      { title: "Mare aux Vacoas — 20 min", description: "The island's largest reservoir, tucked into thick forest — a quiet, scenic pause away from the busier stops." },
      { title: "Grand Bassin — 20 min", description: "The sacred crater lake of Ganga Talao, with its shoreline temple and the 33-metre statue of Lord Shiva, the tallest on the island." },
      { title: "Alexandra Falls — 40 min", description: "A viewpoint deep in the Black River Gorges jungle, looking out over the cloud forest of Mount Cocotte to the south coast." },
      { title: "Black River Gorges National Park — 40 min", description: "The Gorge Viewpoint over 17,000 acres of protected rainforest, rolling hills and a waterfall, along a path lined with souvenir stalls." },
      { title: "Chamarel Seven Coloured Earth Geopark — 2 hr", description: "Mauritius's best-known natural wonder: dunes of naturally banded volcanic earth, reached through roads lined with coffee trees and vetiver. Admission not included." },
      { title: "Return", description: "Back to your hotel or starting point." },
    ],
    tags: ["Nature", "Culture", "Scenery", "Family-friendly"],
    mapArea: { label: "South-west Mauritius — Chamarel & Grand Bassin", query: "Seven Coloured Earths, Chamarel, Mauritius" },
    hero: {
      id: "south-chamarel-hero",
      alt: "The banded dunes of the Seven Coloured Earth Geopark at Chamarel, Mauritius",
      tone: "sunset",
      orientation: "wide",
      src: "/images/tours/south-chamarel-hero.jpg",
    },
    gallery: [
      { id: "south-chamarel-aerial", alt: "Aerial view of the undulating coloured strips of earth at Chamarel", tone: "sunset", orientation: "landscape", src: "/images/tours/south-chamarel-aerial.jpg" },
      { id: "south-chamarel-dunes", alt: "The Seven Coloured Earth dunes and viewing pavilion from above", tone: "sunset", orientation: "landscape", src: "/images/tours/south-chamarel-dunes.jpg" },
      { id: "south-grand-bassin", alt: "Sacred lake of Grand Bassin with temple statues, Mauritius", tone: "forest", orientation: "landscape" },
    ],
    featured: true,
    draft: false,
  },
  {
    slug: "port-louis-north",
    productType: "tour",
    title: "Discover Port Louis & the North of Mauritius",
    hook: "From the bustling capital to the island's prettiest coastal villages.",
    summary:
      "The very best of the north in one route. Wander the Caudan Waterfront and its craft market, take in the colours and aromas of the Central Market, then climb to Fort Adelaide for sweeping views over Port Louis and its harbour. Head north to the centuries-old SSR Botanic Garden and the colonial elegance of Château de Labourdonnais, before reaching the postcard-perfect red-roofed church of Cap Malheureux and unwinding on the white sand of Pereybere Beach.",
    region: "North",
    duration: "5–6 hours",
    fromPrice: 84,
    currency: "USD",
    priceNote: PER_VEHICLE,
    pricing: [
      { vehicle: "Car", capacity: "Up to 3 people", price: 84 },
      { vehicle: "Van", capacity: "5 to 10 people", price: 125 },
    ],
    languages: GUIDE_LANGUAGES,
    accessibility: ["Not wheelchair accessible", "Infants sit on lap"],
    groupType: "Private",
    highlights: [
      "Caudan Waterfront and the Port Louis Central Market",
      "360-degree views from Citadel Fort Adelaide",
      "SSR Botanic Garden, the oldest in the Southern Hemisphere",
      "Château de Labourdonnais and its rum and juice tasting",
      "The red-roofed church at Cap Malheureux",
      "Swimming time at Pereybere Beach",
    ],
    included: [
      "Air-conditioned vehicle",
      "Small bottle of water",
      "Hotel pickup and drop-off",
      "Swimming at Pereybere Beach (optional, at your own risk)",
    ],
    excluded: [
      "Lunch",
      "Entry/admission — SSR Botanic Garden",
      "Entry/admission — Château de Labourdonnais",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Collection from your hotel or accommodation at the time you choose." },
      { title: "Le Caudan Waterfront, Port Louis — 30 min", description: "A harbourfront hub of shopping, dining and marina life on the edge of the capital, with shop-lined walkways beneath colourful hanging umbrellas." },
      { title: "Le Craft Market, Le Caudan Waterfront — 20 min", description: "Mauritian handicrafts, textiles, model ships and spices at prices comparable to the local markets — a good place to pick up a genuine memento." },
      { title: "Port Louis Central Market — 20 min", description: "The beating heart of local life: stalls of tropical fruit, vegetables, spices and flowers, a short walk from the Waterfront." },
      { title: "Citadel Fort Adelaide — 20 min", description: "Built 1834–1840 and now a national monument, with a 360-degree view over the capital, the harbour, the Champ de Mars racecourse and the Moka range." },
      { title: "SSR Botanic Garden, Pamplemousses — 1 hr", description: "The oldest botanical garden in the Southern Hemisphere: 37 hectares, over 500 species, giant water lilies, royal palms and giant tortoises." },
      { title: "Château de Labourdonnais, Mapou — 1 hr", description: "A teak colonial mansion completed in 1859 in Italian neoclassical style, with gardens, orchards and a tasting of the estate's rums, jams and juices." },
      { title: "Cap Malheureux & Notre Dame Auxiliatrice — 20 min", description: "One of the island's most photographed landmarks: a red-roofed church on the water's edge with a holy-water basin made from a giant clamshell." },
      { title: "Pereybere Beach, Grand Baie — 1 hr", description: "Soft white sand and calm turquoise water — sheltered, family-friendly, and the place to unwind before the drive back." },
      { title: "Return", description: "Back to your hotel or starting point." },
    ],
    tags: ["Culture", "History", "Markets", "Beach", "Family-friendly"],
    mapArea: { label: "Port Louis & northern Mauritius", query: "Cap Malheureux, Mauritius" },
    hero: {
      id: "north-pereybere-hero",
      alt: "White sand and calm turquoise water at Pereybere Beach, with Coin de Mire on the horizon",
      tone: "ocean",
      orientation: "wide",
      src: "/images/tours/north-pereybere-hero.jpg",
    },
    gallery: [
      { id: "north-caudan-waterfront", alt: "The colonial waterfront building and palm-lined square at Le Caudan, Port Louis", tone: "sand", orientation: "landscape", src: "/images/tours/north-caudan-waterfront.jpg" },
      { id: "north-coin-de-mire", alt: "Catamarans moored off a northern beach with Coin de Mire island beyond", tone: "lagoon", orientation: "landscape", src: "/images/tours/north-coin-de-mire.jpg" },
      { id: "north-beach-aerial", alt: "Aerial view of a palm-lined northern beach with a jetty and moored boats", tone: "lagoon", orientation: "landscape", src: "/images/tours/north-beach-aerial.jpg" },
      { id: "north-central-market", alt: "Spice and fruit stalls at the Port Louis Central Market", tone: "sand", orientation: "landscape" },
    ],
    featured: true,
    draft: false,
  },
  {
    slug: "vallee-advenature-wild-south",
    productType: "tour",
    title: "Vallée Advenature Park & the Wild South",
    hook: "Ziplines, cliffs and pebble beaches on the island's untamed coast.",
    summary:
      "Beyond the postcard lagoons lies a side of Mauritius few visitors see — a rugged south coast where cliffs meet crashing waves, pebble beaches replace powdery sand and viewpoints stretch for miles. From the adrenaline of La Vallée des Couleurs to the cliffs of Gris Gris, the pebble shore of Rivière des Galets, the outlook at Maconde and the sands of Le Morne beneath its UNESCO-listed mountain.",
    region: "South",
    duration: "Full day",
    fromPrice: 84,
    currency: "USD",
    priceNote: PER_VEHICLE,
    pricing: [
      { vehicle: "Car", capacity: "Up to 3 people", price: 84 },
      { vehicle: "Van", capacity: "5 to 10 people", price: 125 },
    ],
    languages: GUIDE_LANGUAGES,
    groupType: "Private",
    highlights: [
      "Ziplines — the longest in the Indian Ocean",
      "Off-road quad biking, buggy tours and the luge kart",
      "The Nepalese suspension bridge and bicycle zipline",
      "The dramatic cliffs and legends of Gris Gris",
      "Le Morne Beach beneath its UNESCO World Heritage mountain",
    ],
    included: ["Air-conditioned vehicle", "Small bottle of water", "Hotel pickup and drop-off"],
    excluded: [
      "Lunch",
      "Entry/admission at Vallée Advenature Park",
      "Activities at Vallée Advenature Park",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Collection from your hotel or accommodation at the time you choose." },
      { title: "Vallée Advenature Park — 3 hr", description: "La Vallée des Couleurs Nature Park, set against coloured earth and rolling hills. Quad biking, ziplining across canyons, the Nepalese suspension bridge, luge kart and trekking, plus hiking trails and waterfall views." },
      { title: "Gris Gris Beach — 45 min", description: "Where the lagoon ends and the open Indian Ocean begins: jagged cliffs, crashing waves and a coastal walk steeped in local legend." },
      { title: "Rivière des Galets — 15 min", description: "A shoreline of smooth stacked grey pebbles instead of sand, shaped by surf that meets no reef — a favourite among surfers and photographers." },
      { title: "Maconde Viewpoint — 30 min", description: "Perched on the cliffs near Le Morne, with sweeping vistas of the rugged southern coastline meeting the deep blue ocean." },
      { title: "Le Morne Beach — 1 hr", description: "Mauritius at its most postcard-perfect beneath the UNESCO-listed Le Morne Brabant: powder-white sand, palms and clear turquoise water, world-class for kitesurfing." },
      { title: "Return", description: "Back to your hotel or starting point." },
    ],
    tags: ["Adventure", "Nature", "Scenery", "Beach"],
    mapArea: { label: "Southern Mauritius — Chamouny to Le Morne", query: "La Vallée des Couleurs Nature Park, Mauritius" },
    hero: {
      id: "south-le-morne-hero",
      alt: "Le Morne Brabant rising over the turquoise lagoon and palm-lined beach on the south-west coast of Mauritius",
      tone: "sunset",
      orientation: "wide",
      src: "/images/le-morne-aerial.jpg",
      position: "50% 40%", // keeps the summit visible in both the card (4:3) and the detail header (letterbox)
    },
    gallery: [
      { id: "wild-south-luge", alt: "Two riders racing luge karts down the track at Vallée Advenature Park", tone: "forest", orientation: "landscape", src: "/images/tours/wild-south-luge.jpg" },
      { id: "wild-south-zipline", alt: "Two riders on the bicycle zipline above the trees at Vallée Advenature Park", tone: "forest", orientation: "landscape", src: "/images/tours/wild-south-zipline.jpg" },
      { id: "wild-south-nepalese-bridge", alt: "A family crossing the Nepalese suspension bridge at Vallée Advenature Park", tone: "forest", orientation: "landscape", src: "/images/tours/wild-south-nepalese-bridge.jpg" },
      { id: "wild-south-maconde", alt: "The coastal road curving around the rock at the Maconde viewpoint", tone: "ocean", orientation: "landscape", src: "/images/tours/wild-south-maconde.jpg" },
    ],
    featured: true,
    draft: false,
  },
  {
    slug: "ile-aux-cerfs-catamaran",
    productType: "tour",
    title: "Île aux Cerfs Catamaran Day",
    hook: "Sail the east-coast lagoon to a postcard island paradise.",
    summary:
      "A full day on the water: cruise the sheltered east-coast lagoon by catamaran, snorkel over coral, visit the GRSE waterfall from the sea, and relax on the powder-white beaches of Île aux Cerfs with a barbecue lunch on board.",
    region: "East",
    duration: "Full day · about 8 hours",
    fromPrice: 110,
    currency: "USD",
    priceNote: PRICE_NOTE,
    groupType: "Small group",
    highlights: [
      "Catamaran cruise on the east lagoon",
      "Snorkelling over coral gardens",
      "Grand River South East waterfall from the water",
      "Beach time on Île aux Cerfs",
      "Barbecue lunch on board",
    ],
    included: [
      "Return hotel transfers",
      "Catamaran cruise with crew",
      "Snorkelling equipment",
      "Barbecue lunch and soft drinks",
      "Bottled water",
    ],
    excluded: [
      "Water sports on the island",
      "Alcoholic drinks",
      "Gratuities",
      "Personal expenses",
    ],
    itinerary: [
      { title: "Hotel pickup", description: "Transfer to the east-coast departure point." },
      { title: "Set sail", description: "Board the catamaran and cruise into the lagoon." },
      { title: "Snorkel stop", description: "Anchor over coral for snorkelling and swimming." },
      { title: "GRSE waterfall", description: "Approach the Grand River South East waterfall by boat." },
      { title: "Île aux Cerfs", description: "Beach time and barbecue lunch on the island." },
      { title: "Return cruise", description: "Sail back mid-afternoon and transfer to your hotel." },
    ],
    tags: ["Beach", "Snorkelling", "Boat", "Family-friendly"],
    mapArea: { label: "East coast — Île aux Cerfs lagoon", query: "Ile aux Cerfs, Mauritius" },
    hero: { id: "ile-aux-cerfs-hero", alt: "Catamaran under full sail on the turquoise lagoon off the east coast of Mauritius", tone: "lagoon", orientation: "wide", src: "/images/tours/ile-aux-cerfs-hero.jpg" },
    gallery: [
      { id: "cerfs-catamaran", alt: "Catamaran anchored off a white-sand islet in clear turquoise water", tone: "lagoon", orientation: "square", src: "/images/tours/cerfs-catamaran.jpg" },
      { id: "cerfs-bbq", alt: "Barbecue lunch cooking on board with the mountains of the east coast behind", tone: "ocean", orientation: "landscape", src: "/images/tours/cerfs-bbq.jpg" },
      { id: "cerfs-grse-waterfall", alt: "Grand River South East waterfall meeting the sea", tone: "forest", orientation: "landscape" },
    ],
    draft: true,
  },
  {
    slug: "full-island-private-day",
    productType: "tour",
    title: "Full-Island Private Day Tour",
    hook: "Your Mauritius, your way — a private day built around you.",
    summary:
      "A completely bespoke private day: tell us what you want to see — beaches, culture, nature, food, shopping — and we design the route around your interests, with a private vehicle and driver-guide for the whole day.",
    region: "Island-wide",
    duration: "Full day · up to 9 hours",
    fromPrice: 129,
    currency: "USD",
    priceNote: PRICE_NOTE,
    groupType: "Private",
    highlights: [
      "Fully personalised itinerary",
      "Choose your regions and stops",
      "Flexible pace, private vehicle",
      "Local food and hidden-gem recommendations",
      "Ideal for first-time visitors",
    ],
    included: [
      "Private air-conditioned vehicle for the day",
      "Dedicated English-speaking driver-guide",
      "Hotel pickup and drop-off",
      "Bottled water",
      "All road tolls and parking",
    ],
    excluded: [
      "Entrance fees and activities",
      "Lunch and drinks",
      "Gratuities",
      "Personal expenses",
    ],
    itinerary: [
      { title: "Plan together", description: "We agree your priorities and route in advance over WhatsApp or email." },
      { title: "Hotel pickup", description: "Flexible morning start from your hotel." },
      { title: "Your stops", description: "Visit the places you chose, at your own pace." },
      { title: "Lunch", description: "A recommended local spot, or somewhere you have in mind." },
      { title: "Return", description: "Back to your hotel whenever suits you." },
    ],
    tags: ["Private", "Custom", "Flexible", "First visit"],
    mapArea: { label: "Anywhere in Mauritius", query: "Mauritius" },
    hero: { id: "full-island-hero", alt: "Coastal road winding along the Mauritius shoreline with mountains inland", tone: "ocean", orientation: "wide" },
    gallery: [
      { id: "island-beach", alt: "Swimmers in the shallow turquoise water off a white-sand Mauritius beach", tone: "lagoon", orientation: "landscape", src: "/images/tours/island-beach.jpg" },
      { id: "island-mountain", alt: "Le Morne Brabant mountain rising above the lagoon", tone: "ocean", orientation: "portrait", src: "/images/le-morne-aerial.jpg", position: "50% 40%" },
      { id: "island-food", alt: "A street vendor selling freshly fried Mauritian snacks from a glass cabinet", tone: "sunset", orientation: "square", src: "/images/tours/island-food.jpg" },
    ],
    draft: true,
  },
  {
    slug: "five-day-mauritius-package",
    productType: "package",
    title: "Five-Day Mauritius Package",
    hook: "A complete five-day holiday, organised end to end.",
    summary:
      "Our signature five-day package brings together accommodation, airport transfers, guided tours, activities and full travel support — a complete Mauritius holiday planned by one team, then tailored to your interests and budget.",
    region: "Island-wide",
    duration: "5 days · 4 nights",
    fromPrice: 549,
    currency: "USD",
    priceNote: PRICE_NOTE + " (per person, indicative)",
    groupType: "Private",
    highlights: [
      "Accommodation for four nights",
      "Airport transfers included",
      "Two guided tours (north and south)",
      "A lagoon catamaran day",
      "Full travel support throughout",
    ],
    included: [
      "4 nights' accommodation (to your budget)",
      "Return airport transfers",
      "Selected guided tours and activities",
      "Dedicated trip coordinator",
      "24/7 WhatsApp support during your stay",
    ],
    excluded: [
      "International flights (we can arrange these)",
      "Meals not specified",
      "Optional activities",
      "Travel insurance and personal expenses",
    ],
    itinerary: [
      { title: "Day 1 — Arrival", description: "Airport meet & greet, transfer and check-in." },
      { title: "Day 2 — The North", description: "Guided north-island tour and Grand Baie." },
      { title: "Day 3 — Lagoon day", description: "Catamaran cruise and beach time on the east coast." },
      { title: "Day 4 — The South", description: "Chamarel, Grand Bassin and the south circuit." },
      { title: "Day 5 — Departure", description: "Free morning, then transfer to the airport." },
    ],
    tags: ["Package", "All-in-one", "Best value", "Custom"],
    mapArea: { label: "Across Mauritius", query: "Mauritius" },
    hero: { id: "package-hero", alt: "Resort infinity pool overlooking a Mauritius lagoon at sunset", tone: "sunset", orientation: "wide" },
    gallery: [
      { id: "package-resort", alt: "Beachfront resort and palm trees on the Mauritius coast", tone: "lagoon", orientation: "landscape" },
      { id: "package-tour", alt: "Guide and travellers at a scenic Mauritius viewpoint", tone: "forest", orientation: "landscape" },
      { id: "package-catamaran", alt: "Catamaran sailing on a calm turquoise lagoon", tone: "lagoon", orientation: "portrait" },
    ],
    draft: true,
  },
  {
    slug: "airport-transfer-private",
    productType: "transfer",
    title: "Private Airport & Hotel Transfer",
    hook: "A private vehicle and a professional driver, anywhere on the island.",
    summary:
      "Whether you are arriving at the airport or moving between resorts, each ride is a private vehicle with an air-conditioned interior and a professional driver — no shared passengers, no unnecessary stops. A stress-free start or finish to your time in Mauritius, for families, couples and groups alike.",
    region: "Island-wide",
    duration: "One way or return",
    fromPrice: 45,
    currency: "USD",
    priceNote: PER_VEHICLE,
    pricing: [
      { vehicle: "Car", capacity: "Up to 2 people", price: 45 },
      { vehicle: "Van", capacity: "Up to 6 people", price: 120 },
    ],
    groupType: "Private",
    highlights: [
      "SSR Airport to your hotel, or hotel to airport",
      "Inter-hotel and private transfers anywhere in Mauritius",
      "Pickup from any address you choose",
      "Met in arrivals once you have collected your luggage",
      "Private vehicle reserved exclusively for your group",
    ],
    included: [
      "Private air-conditioned vehicle",
      "Professional driver",
      "Door-to-door pickup and drop-off",
      "Bottled water",
    ],
    excluded: ["Meals", "Restroom on board"],
    itinerary: [
      { title: "You send your details", description: "Share your flight and where you are staying when you request the transfer." },
      { title: "We confirm", description: "Once we have your details we confirm the transfer and send everything you need for the journey." },
      { title: "Your driver arrives", description: "On time at the agreed point — in the arrivals area after you collect your luggage, or at your hotel entrance." },
      { title: "Door to door", description: "A direct, comfortable ride to your hotel, accommodation, airport or any location in Mauritius." },
    ],
    tags: ["Transfer", "Airport", "Private", "Reliable"],
    mapArea: { label: "SSR International Airport ⇄ your hotel", query: "Sir Seewoosagur Ramgoolam International Airport, Mauritius" },
    hero: { id: "transfer-hero", alt: "Clean air-conditioned transfer vehicle on a Mauritius coastal road", tone: "ocean", orientation: "wide" },
    gallery: [
      { id: "transfer-meet", alt: "Driver holding a name board in an airport arrivals hall", tone: "ocean", orientation: "landscape" },
      { id: "transfer-interior", alt: "Comfortable air-conditioned vehicle interior", tone: "ocean", orientation: "square" },
    ],
    draft: false,
  },
];
